# Generated by Django 5.1.6 on 2025-10-09 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('idAdditive', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('idBook', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('number_pages', models.IntegerField()),
                ('printing_format', models.CharField(max_length=100)),
                ('color_pages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('identity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('idDelivery', models.AutoField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('idOrder', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('total_price', models.FloatField()),
                ('pay_method', models.CharField(max_length=100)),
                ('done', models.BooleanField()),
                ('payment_advance', models.FloatField()),
                ('outstanding_payment', models.FloatField()),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('idDelivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Book_on_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField()),
                ('ready', models.BooleanField()),
                ('idOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='Requested_book',
            fields=[
                ('idRequested_book', models.AutoField(primary_key=True, serialize=False)),
                ('idBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Requested_book',
            field=models.ManyToManyField(through='core.Book_on_order', to='core.requested_book'),
        ),
        migrations.AddField(
            model_name='book_on_order',
            name='idRequested_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.requested_book'),
        ),
        migrations.CreateModel(
            name='Requested_book_additive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAdditive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.additive')),
                ('idRequested_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.requested_book')),
            ],
        ),
    ]
