# Generated by Django 5.1.6 on 2025-10-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.CharField(max_length=10),
        ),
    ]
