# Generated by Django 5.1.6 on 2025-10-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_delivery_date_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_on_order',
            name='cuantity',
            field=models.IntegerField(default=1),
        ),
    ]
