# Generated by Django 5.1.6 on 2025-10-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_on_order_cuantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_on_order',
            name='cuantity',
            field=models.IntegerField(),
        ),
    ]
