# Generated by Django 5.1.6 on 2025-10-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_book_on_order_cuantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_on_order',
            old_name='cuantity',
            new_name='quantity',
        ),
    ]
