# Generated by Django 5.1.6 on 2025-11-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_cuantity_book_on_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='added_to_excel',
            field=models.BooleanField(default=False),
        ),
    ]
