# Generated by Django 5.1.6 on 2025-11-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_added_to_excel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.AddField(
            model_name='order',
            name='_type',
            field=models.CharField(default='Regular', max_length=100),
        ),
    ]
