# Generated by Django 5.1.6 on 2025-11-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_order_type_order__type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production_costs',
            fields=[
                ('idProduction_costs', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
            ],
        ),
    ]
