# Generated by Django 5.1.6 on 2025-11-20 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identity',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='idClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='idDelivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.delivery'),
        ),
    ]
