# Generated by Django 5.1.6 on 2025-11-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_client_identity_alter_order_idclient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_on_order',
            name='base_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requested_book_additive',
            name='additive_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
